import { PrismaClient } from '@prisma/client'
const p = new PrismaClient()
const r = await p.blogPost.findFirst({ orderBy: { createdAt: 'desc' } })
const text = (r.content || '')
  .replace(/<\/(h2|h3|p|li|tr)>/g, '\n')
  .replace(/<li>/g, ' - ')
  .replace(/<[^>]+>/g, '')
  .replace(/\n{3,}/g, '\n\n')
console.log('제목:', r.title)
console.log('요약:', r.excerpt)
console.log('\n=== 본문 ===\n')
console.log(text.trim())
await p.$disconnect()
